### Variables de entorno
@baseUrl = localhost:777
###

### POST para registrar un usuario
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "data": {
    "phone": "12345678901",
    "password": "123456",
    "username": "qje mamadota ya jalo"
  }
}
###

### POST para iniciar sesión
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "phone": "12345678901",
    "password": "123456"
}
> {%
    client.global.set("token", response.body.data.token);
%}
