
### Variables de entorno
@baseUrl = localhost:777/users
###


### GET para obtener todos los usuarios
GET {{baseUrl}}/all
###


### POST para buscar un usuario por su id
GET {{baseUrl}}/286a2c3e-4a15-4cc5-b148-5515e19f9565


###

### GET de usuario por su telefono
GET {{baseUrl}}/phone/8714980534

###


### DELETE para eliminar un usuario
DELETE {{baseUrl}}/209c78f7-d89d-4a97-b4a5-93dda0f7ce8d

###
